<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LapisanPenghasilanBrutoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kode_ptkp_a = 'TK/0;TK/1;K/0;';
        $kategori_a = 'Ter A';
        $ter_a = [
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 0,
                'nominal_end' => 5400000,
                'pengali' => 0.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 5400001,
                'nominal_end' => 5650000,
                'pengali' => 0.25,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 5650001,
                'nominal_end' => 5950000,
                'pengali' => 0.50,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 5950001,
                'nominal_end' => 6300000,
                'pengali' => 0.75,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 6300001,
                'nominal_end' => 6750000,
                'pengali' => 1.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 6750001,
                'nominal_end' => 7500000,
                'pengali' => 1.25,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 7500001,
                'nominal_end' => 8550000,
                'pengali' => 1.50,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 8550001,
                'nominal_end' => 9650000,
                'pengali' => 1.75,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 9650001,
                'nominal_end' => 10050000,
                'pengali' => 2.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 10050001,
                'nominal_end' => 10350000,
                'pengali' => 2.25,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 10350001,
                'nominal_end' => 10700000,
                'pengali' => 2.50,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 10700001,
                'nominal_end' => 11050000,
                'pengali' => 3.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 11050001,
                'nominal_end' => 11600000,
                'pengali' => 3.50,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 11600001,
                'nominal_end' => 12500000,
                'pengali' => 4.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 12500001,
                'nominal_end' => 13750000,
                'pengali' => 5.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 13750001,
                'nominal_end' => 15100000,
                'pengali' => 6.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 15100001,
                'nominal_end' => 16950000,
                'pengali' => 7.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 16950001,
                'nominal_end' => 19750000,
                'pengali' => 8.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 19750001,
                'nominal_end' => 24150000,
                'pengali' => 9.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 24150001,
                'nominal_end' => 26450000,
                'pengali' => 10.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 26450001,
                'nominal_end' => 28000000,
                'pengali' => 11.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 28000001,
                'nominal_end' => 30050000,
                'pengali' => 12.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 30050001,
                'nominal_end' => 32400000,
                'pengali' => 13.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 32400001,
                'nominal_end' => 35400000,
                'pengali' => 14.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 35400001,
                'nominal_end' => 39100000,
                'pengali' => 15.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 39100001,
                'nominal_end' => 43850000,
                'pengali' => 16.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 43850001,
                'nominal_end' => 47800000,
                'pengali' => 17.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 47800001,
                'nominal_end' => 51400000,
                'pengali' => 18.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 51400001,
                'nominal_end' => 56300000,
                'pengali' => 19.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 56300001,
                'nominal_end' => 62200000,
                'pengali' => 20.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 62200001,
                'nominal_end' => 68600000,
                'pengali' => 21.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 68600001,
                'nominal_end' => 77500000,
                'pengali' => 22.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 77500001,
                'nominal_end' => 89000000,
                'pengali' => 23.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 89000001,
                'nominal_end' => 103000000,
                'pengali' => 24.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 103000001,
                'nominal_end' => 125000000,
                'pengali' => 25.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 125000001,
                'nominal_end' => 157000000,
                'pengali' => 26.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 157000001,
                'nominal_end' => 206000000,
                'pengali' => 27.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 206000001,
                'nominal_end' => 337000000,
                'pengali' => 28.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 337000001,
                'nominal_end' => 454000000,
                'pengali' => 29.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 454000001,
                'nominal_end' => 550000000,
                'pengali' => 30.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 550000001,
                'nominal_end' => 695000000,
                'pengali' => 31.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 695000001,
                'nominal_end' => 910000000,
                'pengali' => 32.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 910000001,
                'nominal_end' => 1400000000,
                'pengali' => 33.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_a,
                'kategori' => $kategori_a,
                'nominal_start' => 1400000001,
                'nominal_end' => 0,
                'pengali' => 34.00,
            ],
        ];

        $kode_ptkp_b = 'TK/2;K/1;TK/3;K/2;';
        $kategori_b = 'Ter B';
        $ter_b = [
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 0,
                'nominal_end' => 6200000,
                'pengali' => 0.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 6200001,
                'nominal_end' => 6500000,
                'pengali' => 0.25,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 6500001,
                'nominal_end' => 6850000,
                'pengali' => 0.50,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 6850001,
                'nominal_end' => 7300000,
                'pengali' => 0.75,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 7300001,
                'nominal_end' => 9200000,
                'pengali' => 1.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 9200001,
                'nominal_end' => 10750000,
                'pengali' => 1.50,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 10750001,
                'nominal_end' => 11250000,
                'pengali' => 2.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 11250001,
                'nominal_end' => 11600000,
                'pengali' => 2.50,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 11600001,
                'nominal_end' => 12600000,
                'pengali' => 3.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 12600001,
                'nominal_end' => 13600000,
                'pengali' => 4.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 13600001,
                'nominal_end' => 14950000,
                'pengali' => 5.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 14950001,
                'nominal_end' => 16400000,
                'pengali' => 6.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 16400001,
                'nominal_end' => 18450000,
                'pengali' => 7.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 18450001,
                'nominal_end' => 21850000,
                'pengali' => 8.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 21850001,
                'nominal_end' => 26000000,
                'pengali' => 9.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 26000001,
                'nominal_end' => 27700000,
                'pengali' => 10.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 27700001,
                'nominal_end' => 29350000,
                'pengali' => 11.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 29350001,
                'nominal_end' => 31450000,
                'pengali' => 12.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 31450001,
                'nominal_end' => 33950000,
                'pengali' => 13.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 33950001,
                'nominal_end' => 37100000,
                'pengali' => 14.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 37100001,
                'nominal_end' => 41100000,
                'pengali' => 15.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 41100001,
                'nominal_end' => 45800000,
                'pengali' => 16.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 45800001,
                'nominal_end' => 49500000,
                'pengali' => 17.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 49500001,
                'nominal_end' => 53800000,
                'pengali' => 18.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 53800001,
                'nominal_end' => 58500000,
                'pengali' => 19.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 58500001,
                'nominal_end' => 64000000,
                'pengali' => 20.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 64000001,
                'nominal_end' => 71000000,
                'pengali' => 21.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 71000001,
                'nominal_end' => 80000000,
                'pengali' => 22.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 80000001,
                'nominal_end' => 93000000,
                'pengali' => 23.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 93000001,
                'nominal_end' => 109000000,
                'pengali' => 24.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 109000001,
                'nominal_end' => 129000000,
                'pengali' => 25.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 129000001,
                'nominal_end' => 163000000,
                'pengali' => 26.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 163000001,
                'nominal_end' => 211000000,
                'pengali' => 27.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 211000001,
                'nominal_end' => 374000000,
                'pengali' => 28.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 374000001,
                'nominal_end' => 459000000,
                'pengali' => 29.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 459000001,
                'nominal_end' => 555000000,
                'pengali' => 30.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 555000001,
                'nominal_end' => 704000000,
                'pengali' => 31.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 704000001,
                'nominal_end' => 957000000,
                'pengali' => 32.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 957000001,
                'nominal_end' => 1405000000,
                'pengali' => 33.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_b,
                'kategori' => $kategori_b,
                'nominal_start' => 1405000001,
                'nominal_end' => 0,
                'pengali' => 34.00,
            ],
        ];

        $kode_ptkp_c = 'K/3;';
        $kategori_c = 'Ter C';
        $ter_c = [
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 0,
                'nominal_end' => 6600000,
                'pengali' => 0.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 6600001,
                'nominal_end' => 6950000,
                'pengali' => 0.25,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 6950001,
                'nominal_end' => 7350000,
                'pengali' => 0.50,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 7350001,
                'nominal_end' => 7800000,
                'pengali' => 0.75,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 7800001,
                'nominal_end' => 8850000,
                'pengali' => 1.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 8850001,
                'nominal_end' => 9800000,
                'pengali' => 1.25,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 9800001,
                'nominal_end' => 10950000,
                'pengali' => 1.50,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 10950001,
                'nominal_end' => 11200000,
                'pengali' => 1.75,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 11200001,
                'nominal_end' => 12050000,
                'pengali' => 2.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 12050001,
                'nominal_end' => 12950000,
                'pengali' => 3.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 12950001,
                'nominal_end' => 14150000,
                'pengali' => 4.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 14150001,
                'nominal_end' => 15550000,
                'pengali' => 5.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 15550001,
                'nominal_end' => 17050000,
                'pengali' => 6.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 17050001,
                'nominal_end' => 19500000,
                'pengali' => 7.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 19500001,
                'nominal_end' => 22700000,
                'pengali' => 8.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 22700001,
                'nominal_end' => 26600000,
                'pengali' => 9.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 26600001,
                'nominal_end' => 28100000,
                'pengali' => 10.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 28100001,
                'nominal_end' => 30100000,
                'pengali' => 11.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 30100001,
                'nominal_end' => 32600000,
                'pengali' => 12.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 32600001,
                'nominal_end' => 35400000,
                'pengali' => 13.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 35400001,
                'nominal_end' => 38900000,
                'pengali' => 14.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 38900001,
                'nominal_end' => 43000000,
                'pengali' => 15.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 43000001,
                'nominal_end' => 47400000,
                'pengali' => 16.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 47400001,
                'nominal_end' => 51200000,
                'pengali' => 17.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 51200001,
                'nominal_end' => 55800000,
                'pengali' => 18.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 55800001,
                'nominal_end' => 60400000,
                'pengali' => 19.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 60400001,
                'nominal_end' => 66700000,
                'pengali' => 20.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 66700001,
                'nominal_end' => 74500000,
                'pengali' => 21.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 74500001,
                'nominal_end' => 83200000,
                'pengali' => 22.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 83200001,
                'nominal_end' => 95600000,
                'pengali' => 23.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 95600001,
                'nominal_end' => 110000000,
                'pengali' => 24.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 110000001,
                'nominal_end' => 134000000,
                'pengali' => 25.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 134000001,
                'nominal_end' => 169000000,
                'pengali' => 26.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 169000001,
                'nominal_end' => 221000000,
                'pengali' => 27.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 221000001,
                'nominal_end' => 390000000,
                'pengali' => 28.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 390000001,
                'nominal_end' => 463000000,
                'pengali' => 29.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 463000001,
                'nominal_end' => 561000000,
                'pengali' => 30.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 561000001,
                'nominal_end' => 709000000,
                'pengali' => 31.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 709000001,
                'nominal_end' => 965000000,
                'pengali' => 32.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 965000001,
                'nominal_end' => 1419000000,
                'pengali' => 33.00,
            ],
            [
                'kode_ptkp' => $kode_ptkp_c,
                'kategori' => $kategori_c,
                'nominal_start' => 1419000001,
                'nominal_end' => 0,
                'pengali' => 34.00,
            ],
        ];

        $all_arr = array_merge($ter_a, $ter_b, $ter_c);
        for ($i=0; $i < count($all_arr); $i++) { 
            DB::table('lapisan_penghasilan_bruto')->insert($all_arr[$i]);
        }
    }
}
