<table>
    <thead>
        <tr>
            <th align="center"
                style="width: 100px; background-color: #EEECE1; font-weight: bold; border: 1px solid black;">KODE</th>
            <th align="center"
                style="width: 250px; background-color: #EEECE1; font-weight: bold; border: 1px solid black;">Nama Negara
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>AFG</td>
            <td>Afghanistan</td>
        </tr>
        <tr>
            <td>AGO</td>
            <td>Angola</td>
        </tr>
        <tr>
            <td>ALB</td>
            <td>Albania</td>
        </tr>
        <tr>
            <td>AND</td>
            <td>Andorra</td>
        </tr>
        <tr>
            <td>ARE</td>
            <td>United Arab Emirates</td>
        </tr>
        <tr>
            <td>ARG</td>
            <td>Argentina</td>
        </tr>
        <tr>
            <td>ARM</td>
            <td>Armenia</td>
        </tr>
        <tr>
            <td>ATG</td>
            <td>Antigua dan Barbuda</td>
        </tr>
        <tr>
            <td>AUS</td>
            <td>Australia</td>
        </tr>
        <tr>
            <td>AUT</td>
            <td>Austria</td>
        </tr>
        <tr>
            <td>AZE</td>
            <td>Azerbaijan</td>
        </tr>
        <tr>
            <td>BDI</td>
            <td>Burundi</td>
        </tr>
        <tr>
            <td>BEL</td>
            <td>Belgium</td>
        </tr>
        <tr>
            <td>BEN</td>
            <td>Benin</td>
        </tr>
        <tr>
            <td>BFA</td>
            <td>Burkina Faso</td>
        </tr>
        <tr>
            <td>BGD</td>
            <td>Bangladesh</td>
        </tr>
        <tr>
            <td>BGR</td>
            <td>Bulgaria</td>
        </tr>
        <tr>
            <td>BHR</td>
            <td>Bahrain</td>
        </tr>
        <tr>
            <td>BHS</td>
            <td>Bahamas</td>
        </tr>
        <tr>
            <td>BIH</td>
            <td>Bosnia dan Herzegovina</td>
        </tr>
        <tr>
            <td>BLR</td>
            <td>Belarus</td>
        </tr>
        <tr>
            <td>BLZ</td>
            <td>Belize</td>
        </tr>
        <tr>
            <td>BOL</td>
            <td>Bolivia</td>
        </tr>
        <tr>
            <td>BRA</td>
            <td>Brazil</td>
        </tr>
        <tr>
            <td>BRB</td>
            <td>Barbados</td>
        </tr>
        <tr>
            <td>BRN</td>
            <td>Brunei Darussalam</td>
        </tr>
        <tr>
            <td>BTN</td>
            <td>Bhutan</td>
        </tr>
        <tr>
            <td>BWA</td>
            <td>Bostwana</td>
        </tr>
        <tr>
            <td>CAF</td>
            <td>Central African Republic</td>
        </tr>
        <tr>
            <td>CAN</td>
            <td>Canada</td>
        </tr>
        <tr>
            <td>CHE</td>
            <td>Switzerland</td>
        </tr>
        <tr>
            <td>CHL</td>
            <td>Chile</td>
        </tr>
        <tr>
            <td>CHN</td>
            <td>China</td>
        </tr>
        <tr>
            <td>CIV</td>
            <td>Pantai Gading</td>
        </tr>
        <tr>
            <td>CMR</td>
            <td>Cameroon</td>
        </tr>
        <tr>
            <td>COD</td>
            <td>Congo - the Democratic Republic of the</td>
        </tr>
        <tr>
            <td>COG</td>
            <td>Congo</td>
        </tr>
        <tr>
            <td>COL</td>
            <td>Colombia</td>
        </tr>
        <tr>
            <td>COM</td>
            <td>Comoros</td>
        </tr>
        <tr>
            <td>CPV</td>
            <td>Cabo Verde</td>
        </tr>
        <tr>
            <td>CRI</td>
            <td>Costa Rica</td>
        </tr>
        <tr>
            <td>CUB</td>
            <td>Cuba</td>
        </tr>
        <tr>
            <td>CYP</td>
            <td>Cyprus</td>
        </tr>
        <tr>
            <td>CZE</td>
            <td>Republik Ceko</td>
        </tr>
        <tr>
            <td>DEU</td>
            <td>Germany</td>
        </tr>
        <tr>
            <td>DJI</td>
            <td>Djibouti</td>
        </tr>
        <tr>
            <td>DMA</td>
            <td>Dominica</td>
        </tr>
        <tr>
            <td>DNK</td>
            <td>Denmark</td>
        </tr>
        <tr>
            <td>DOM</td>
            <td>Dominican Republic</td>
        </tr>
        <tr>
            <td>DSA</td>
            <td>Aljazair</td>
        </tr>
        <tr>
            <td>ECU</td>
            <td>Ekuador</td>
        </tr>
        <tr>
            <td>EGY</td>
            <td>Egypt</td>
        </tr>
        <tr>
            <td>ERI</td>
            <td>Eritrea</td>
        </tr>
        <tr>
            <td>ESP</td>
            <td>Spain</td>
        </tr>
        <tr>
            <td>EST</td>
            <td>Estonia</td>
        </tr>
        <tr>
            <td>ETH</td>
            <td>Ethiopia</td>
        </tr>
        <tr>
            <td>FIN</td>
            <td>Finlandia</td>
        </tr>
        <tr>
            <td>FJI</td>
            <td>Fiji</td>
        </tr>
        <tr>
            <td>FRA</td>
            <td>France</td>
        </tr>
        <tr>
            <td>FSM</td>
            <td>Micronesia</td>
        </tr>
        <tr>
            <td>GAB</td>
            <td>Gabon</td>
        </tr>
        <tr>
            <td>GBR</td>
            <td>United Kingdom</td>
        </tr>
        <tr>
            <td>GEO</td>
            <td>Georgia</td>
        </tr>
        <tr>
            <td>GHA</td>
            <td>Ghana</td>
        </tr>
        <tr>
            <td>GIN</td>
            <td>Guinea</td>
        </tr>
        <tr>
            <td>GMB</td>
            <td>Gambia</td>
        </tr>
        <tr>
            <td>GNB</td>
            <td>Guinea-Bissau</td>
        </tr>
        <tr>
            <td>GNQ</td>
            <td>Equatorial Guinea</td>
        </tr>
        <tr>
            <td>GRC</td>
            <td>Greece</td>
        </tr>
        <tr>
            <td>GRD</td>
            <td>Grenada</td>
        </tr>
        <tr>
            <td>GTM</td>
            <td>Guatemala</td>
        </tr>
        <tr>
            <td>GUY</td>
            <td>Guyana</td>
        </tr>
        <tr>
            <td>HKG</td>
            <td>Hong Kong</td>
        </tr>
        <tr>
            <td>HND</td>
            <td>Honduras</td>
        </tr>
        <tr>
            <td>HRV</td>
            <td>Croatia</td>
        </tr>
        <tr>
            <td>HTI</td>
            <td>Haiti</td>
        </tr>
        <tr>
            <td>HUN</td>
            <td>Hungary</td>
        </tr>
        <tr>
            <td>IND</td>
            <td>India</td>
        </tr>
        <tr>
            <td>IRL</td>
            <td>Irlandia</td>
        </tr>
        <tr>
            <td>IRN</td>
            <td>Iran</td>
        </tr>
        <tr>
            <td>IRQ</td>
            <td>Iraq</td>
        </tr>
        <tr>
            <td>ISL</td>
            <td>Iceland</td>
        </tr>
        <tr>
            <td>ISR</td>
            <td>Israel</td>
        </tr>
        <tr>
            <td>ITA</td>
            <td>Italy</td>
        </tr>
        <tr>
            <td>JAM</td>
            <td>Jamaica</td>
        </tr>
        <tr>
            <td>JOR</td>
            <td>Jordan</td>
        </tr>
        <tr>
            <td>JPN</td>
            <td>Japan</td>
        </tr>
        <tr>
            <td>KAZ</td>
            <td>Kazakhstan</td>
        </tr>
        <tr>
            <td>KEN</td>
            <td>Kenya</td>
        </tr>
        <tr>
            <td>KGZ</td>
            <td>Kyrgyzstan</td>
        </tr>
        <tr>
            <td>KHM</td>
            <td>Cambodia</td>
        </tr>
        <tr>
            <td>KIR</td>
            <td>Kiribati</td>
        </tr>
        <tr>
            <td>KNA</td>
            <td>Saint Kitts dan Nevis</td>
        </tr>
        <tr>
            <td>KOR</td>
            <td>Korea, Republic of</td>
        </tr>
        <tr>
            <td>KWT</td>
            <td>Kuwait</td>
        </tr>
        <tr>
            <td>LAO</td>
            <td>Laos</td>
        </tr>
        <tr>
            <td>LBN</td>
            <td>Lebanon</td>
        </tr>
        <tr>
            <td>LBR</td>
            <td>Liberia</td>
        </tr>
        <tr>
            <td>LBY</td>
            <td>Libya</td>
        </tr>
        <tr>
            <td>LCA</td>
            <td>Saint Lucia</td>
        </tr>
        <tr>
            <td>LIE</td>
            <td>Liechtenstein</td>
        </tr>
        <tr>
            <td>LKA</td>
            <td>Sri Lanka</td>
        </tr>
        <tr>
            <td>LSO</td>
            <td>Lesotho</td>
        </tr>
        <tr>
            <td>LTU</td>
            <td>Lituania</td>
        </tr>
        <tr>
            <td>LUX</td>
            <td>Luxembourg</td>
        </tr>
        <tr>
            <td>LVA</td>
            <td>Latvia</td>
        </tr>
        <tr>
            <td>MAR</td>
            <td>Morocco</td>
        </tr>
        <tr>
            <td>MCO</td>
            <td>Monaco</td>
        </tr>
        <tr>
            <td>MDA</td>
            <td>Moldova, Republic of</td>
        </tr>
        <tr>
            <td>MDG</td>
            <td>Madagascar</td>
        </tr>
        <tr>
            <td>MDV</td>
            <td>Maldives</td>
        </tr>
        <tr>
            <td>MEX</td>
            <td>Mexico</td>
        </tr>
        <tr>
            <td>MHL</td>
            <td>Marshall Islands</td>
        </tr>
        <tr>
            <td>MKD</td>
            <td>Macedonia</td>
        </tr>
        <tr>
            <td>MLI</td>
            <td>Mali</td>
        </tr>
        <tr>
            <td>MLT</td>
            <td>Malta</td>
        </tr>
        <tr>
            <td>MMR</td>
            <td>Myanmar</td>
        </tr>
        <tr>
            <td>MNE</td>
            <td>Montenegro</td>
        </tr>
        <tr>
            <td>MNG</td>
            <td>Mongolia</td>
        </tr>
        <tr>
            <td>MOZ</td>
            <td>Mozambique</td>
        </tr>
        <tr>
            <td>MRT</td>
            <td>Mauritania</td>
        </tr>
        <tr>
            <td>MUS</td>
            <td>Mauritius</td>
        </tr>
        <tr>
            <td>MWI</td>
            <td>Malawi</td>
        </tr>
        <tr>
            <td>MYS</td>
            <td>Malaysia</td>
        </tr>
        <tr>
            <td>NAM</td>
            <td>Namibia</td>
        </tr>
        <tr>
            <td>NER</td>
            <td>Niger</td>
        </tr>
        <tr>
            <td>NGA</td>
            <td>Nigeria</td>
        </tr>
        <tr>
            <td>NIC</td>
            <td>Nicaragua</td>
        </tr>
        <tr>
            <td>NLD</td>
            <td>Netherlands</td>
        </tr>
        <tr>
            <td>NOR</td>
            <td>Norway</td>
        </tr>
        <tr>
            <td>NOR</td>
            <td>Norway</td>
        </tr>
        <tr>
            <td>NPL</td>
            <td>Nepal</td>
        </tr>
        <tr>
            <td>NRU</td>
            <td>Nauru</td>
        </tr>
        <tr>
            <td>NZL</td>
            <td>New Zealand</td>
        </tr>
        <tr>
            <td>OMN</td>
            <td>Oman</td>
        </tr>
        <tr>
            <td>PAK</td>
            <td>Pakistan</td>
        </tr>
        <tr>
            <td>PAN</td>
            <td>Panama</td>
        </tr>
        <tr>
            <td>PER</td>
            <td>Peru</td>
        </tr>
        <tr>
            <td>PHL</td>
            <td>Philippines</td>
        </tr>
        <tr>
            <td>PLW</td>
            <td>Palau</td>
        </tr>
        <tr>
            <td>PNG</td>
            <td>Papua New Guinea</td>
        </tr>
        <tr>
            <td>POL</td>
            <td>Poland</td>
        </tr>
        <tr>
            <td>PRK</td>
            <td>North Korea</td>
        </tr>
        <tr>
            <td>PRT</td>
            <td>Portugal</td>
        </tr>
        <tr>
            <td>PRY</td>
            <td>Paraguay</td>
        </tr>
        <tr>
            <td>QAT</td>
            <td>Qatar</td>
        </tr>
        <tr>
            <td>ROU</td>
            <td>Romania</td>
        </tr>
        <tr>
            <td>RUS</td>
            <td>Russian Federation</td>
        </tr>
        <tr>
            <td>RWA</td>
            <td>Rwanda</td>
        </tr>
        <tr>
            <td>SAU</td>
            <td>Saudi Arabia</td>
        </tr>
        <tr>
            <td>SDN</td>
            <td>Sudan</td>
        </tr>
        <tr>
            <td>SEN</td>
            <td>Senegal</td>
        </tr>
        <tr>
            <td>SGP</td>
            <td>Singapore</td>
        </tr>
        <tr>
            <td>SLB</td>
            <td>Solomon Islands</td>
        </tr>
        <tr>
            <td>SLE</td>
            <td>Sierra Leone</td>
        </tr>
        <tr>
            <td>SLV</td>
            <td>El Salvador</td>
        </tr>
        <tr>
            <td>SMR</td>
            <td>San Marino</td>
        </tr>
        <tr>
            <td>SOM</td>
            <td>Somalia</td>
        </tr>
        <tr>
            <td>SRB</td>
            <td>Serbia</td>
        </tr>
        <tr>
            <td>STP</td>
            <td>Sao Tome dan Principe</td>
        </tr>
        <tr>
            <td>SUR</td>
            <td>Suriname</td>
        </tr>
        <tr>
            <td>SVK</td>
            <td>Slovakia</td>
        </tr>
        <tr>
            <td>SVN</td>
            <td>Slovenia</td>
        </tr>
        <tr>
            <td>SWE</td>
            <td>Sweden</td>
        </tr>
        <tr>
            <td>SWZ</td>
            <td>Swaziland</td>
        </tr>
        <tr>
            <td>SYC</td>
            <td>Seychelles</td>
        </tr>
        <tr>
            <td>SYR</td>
            <td>Syria</td>
        </tr>
        <tr>
            <td>TCD</td>
            <td>Chad</td>
        </tr>
        <tr>
            <td>TGO</td>
            <td>Togo</td>
        </tr>
        <tr>
            <td>THA</td>
            <td>Thailand</td>
        </tr>
        <tr>
            <td>TJK</td>
            <td>Tajikistan</td>
        </tr>
        <tr>
            <td>TKM</td>
            <td>Turkmenistan</td>
        </tr>
        <tr>
            <td>TLS</td>
            <td>Timor Leste</td>
        </tr>
        <tr>
            <td>TON</td>
            <td>Tonga</td>
        </tr>
        <tr>
            <td>TTO</td>
            <td>Trinidad dan Tobago</td>
        </tr>
        <tr>
            <td>TUN</td>
            <td>Tunisia</td>
        </tr>
        <tr>
            <td>TUR</td>
            <td>Turkey</td>
        </tr>
        <tr>
            <td>TUV</td>
            <td>Tuvalu</td>
        </tr>
        <tr>
            <td>TWN</td>
            <td>Taiwan</td>
        </tr>
        <tr>
            <td>TZA</td>
            <td>Tanzania</td>
        </tr>
        <tr>
            <td>UGA</td>
            <td>Uganda</td>
        </tr>
        <tr>
            <td>UKR</td>
            <td>Ukraine</td>
        </tr>
        <tr>
            <td>URY</td>
            <td>Uruguay</td>
        </tr>
        <tr>
            <td>USA</td>
            <td>United States</td>
        </tr>
        <tr>
            <td>UZB</td>
            <td>Uzbekistan</td>
        </tr>
        <tr>
            <td>VAT</td>
            <td>Vatican</td>
        </tr>
        <tr>
            <td>VCT</td>
            <td>Saint Vincent dan Grenadines</td>
        </tr>
        <tr>
            <td>VEN</td>
            <td>Venezuela</td>
        </tr>
        <tr>
            <td>VNM</td>
            <td>Viet Nam</td>
        </tr>
        <tr>
            <td>VUT</td>
            <td>Vanuatu</td>
        </tr>
        <tr>
            <td>WSM</td>
            <td>Samoa</td>
        </tr>
        <tr>
            <td>YEM</td>
            <td>Yemen</td>
        </tr>
        <tr>
            <td>ZAF</td>
            <td>South Africa</td>
        </tr>
        <tr>
            <td>ZMB</td>
            <td>Zambia</td>
        </tr>
        <tr>
            <td>ZWE</td>
            <td>Zimbabwe</td>
        </tr>
        <tr>
            <td>VGB</td>
            <td>Virgin Islands, British</td>
        </tr>
        <tr>
            <td>VIR</td>
            <td>Virgin Islands, US</td>
        </tr>
        <tr>
            <td>UMI</td>
            <td>United States Minor Outlying Islands</td>
        </tr>
        <tr>
            <td>TKL</td>
            <td>Tokelau</td>
        </tr>
        <tr>
            <td>SPM</td>
            <td>Saint Pierre and Miquelon</td>
        </tr>
        <tr>
            <td>SJM</td>
            <td>Svalbard and Jan Mayen</td>
        </tr>
        <tr>
            <td>SHN</td>
            <td>Saint Helena, Ascension and Tristan da Cunha</td>
        </tr>
        <tr>
            <td>SHN</td>
            <td>Saint Helena, Ascension and Tristan da Cunha</td>
        </tr>
        <tr>
            <td>SGS</td>
            <td>South Georgia and the South Sandwich Islands</td>
        </tr>
        <tr>
            <td>REU</td>
            <td>Réunion</td>
        </tr>
        <tr>
            <td>PYF</td>
            <td>French Polynesia</td>
        </tr>
        <tr>
            <td>PSE</td>
            <td>Palestine, State of</td>
        </tr>
        <tr>
            <td>ABW</td>
            <td>Aruba</td>
        </tr>
        <tr>
            <td>AIA</td>
            <td>Anguilla</td>
        </tr>
        <tr>
            <td>ALA</td>
            <td>Åland Islands</td>
        </tr>
        <tr>
            <td>ASM</td>
            <td>American Samoa</td>
        </tr>
        <tr>
            <td>ATA</td>
            <td>Antarctica</td>
        </tr>
        <tr>
            <td>ATF</td>
            <td>French Southern Territories</td>
        </tr>
        <tr>
            <td>BES</td>
            <td>Bonaire, Sint Eustatius and Saba</td>
        </tr>
        <tr>
            <td>BLM</td>
            <td>Saint Barthélemy</td>
        </tr>
        <tr>
            <td>BMU</td>
            <td>Bermuda</td>
        </tr>
        <tr>
            <td>BVT</td>
            <td>Bouvet Island</td>
        </tr>
        <tr>
            <td>CCK</td>
            <td>Cocos (Keeling) Islands</td>
        </tr>
        <tr>
            <td>COK</td>
            <td>Cook Islands</td>
        </tr>
        <tr>
            <td>CUW</td>
            <td>Curaçao</td>
        </tr>
        <tr>
            <td>CXR</td>
            <td>Christmas Island</td>
        </tr>
        <tr>
            <td>CYM</td>
            <td>Cayman Islands</td>
        </tr>
        <tr>
            <td>DZA</td>
            <td>Algeria</td>
        </tr>
        <tr>
            <td>ESH</td>
            <td>Western Sahara</td>
        </tr>
        <tr>
            <td>FLK</td>
            <td>Falkland Islands (Malvinas)</td>
        </tr>
        <tr>
            <td>FRO</td>
            <td>Faroe Islands</td>
        </tr>
        <tr>
            <td>GGY</td>
            <td>Guernsey</td>
        </tr>
        <tr>
            <td>GIB</td>
            <td>Gibraltar</td>
        </tr>
        <tr>
            <td>GRL</td>
            <td>Greenland</td>
        </tr>
        <tr>
            <td>GUF</td>
            <td>French Guiana</td>
        </tr>
        <tr>
            <td>GUM</td>
            <td>Guam</td>
        </tr>
        <tr>
            <td>HMD</td>
            <td>Heard Island and McDonald Islands</td>
        </tr>
        <tr>
            <td>IMN</td>
            <td>Isle of Man</td>
        </tr>
        <tr>
            <td>IOT</td>
            <td>British Indian Ocean Territory</td>
        </tr>
        <tr>
            <td>JEY</td>
            <td>Jersey</td>
        </tr>
        <tr>
            <td>MAC</td>
            <td>Macao</td>
        </tr>
        <tr>
            <td>MAF</td>
            <td>Saint Martin</td>
        </tr>
        <tr>
            <td>MNP</td>
            <td>Northern Mariana Islands</td>
        </tr>
        <tr>
            <td>MSR</td>
            <td>Montserrat</td>
        </tr>
        <tr>
            <td>MTQ</td>
            <td>Martinique</td>
        </tr>
        <tr>
            <td>MYT</td>
            <td>Mayotte</td>
        </tr>
        <tr>
            <td>NCL</td>
            <td>New Caledonia</td>
        </tr>
        <tr>
            <td>NFK</td>
            <td>Norfolk Island</td>
        </tr>
        <tr>
            <td>NIU</td>
            <td>Niue</td>
        </tr>
        <tr>
            <td>PCN</td>
            <td>Pitcairn</td>
        </tr>
        <tr>
            <td>PRI</td>
            <td>Puerto Rico</td>
        </tr>
        <tr>
            <td>SSD</td>
            <td>South Sudan</td>
        </tr>
        <tr>
            <td>SXM</td>
            <td>Sint Maarten (Dutch part)</td>
        </tr>
        <tr>
            <td>TCA</td>
            <td>Turks and Caicos Islands</td>
        </tr>
        <tr>
            <td>WLF</td>
            <td>Wallis and Futuna</td>
        </tr>
    </tbody>
</table>
